=== lionsoft/ehealth.api/apps/ehealth/specs/json_schemas/medication_request_request/medication_request_request_create_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "date": {
      "type": "string",
      "pattern": "^(\\d{4}(?!\\d{2}\\b))((-)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6]))))$"
    },
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$"
    }
  },
  "type": "object",
  "properties": {
    "person_id": {
      "$ref": "#/definitions/uuid",
      "description": "Person identifier"
    },
    "employee_id": {
      "$ref": "#/definitions/uuid",
      "description": "Employee ID with `type=DOCTOR` who issued Medication Request."
    },
    "division_id": {
      "$ref": "#/definitions/uuid",
      "description": "Division identifier"
    },
    "created_at": {
      "$ref": "#/definitions/date",
      "description": "Medication request creation date, which is determined by the external system. Format DATE '2017-09-07'"
    },
    "started_at": {
      "$ref": "#/definitions/date",
      "description": "Start date of a treatment period, which is determined by the external system. Greater or equal to created_at. Format DATE '2017-09-07'"
    },
    "ended_at": {
      "$ref": "#/definitions/date",
      "description": "End date of a treatment period, which is determined by the external system. Greater or equal to started_at. Format DATE '2017-10-07'"
    },
    "dispense_valid_from": {
      "$ref": "#/definitions/date",
      "description": "Start date of dispense period, which is determined by the external system. Format DATE '2017-09-07'"
    },
    "dispense_valid_to": {
      "$ref": "#/definitions/date",
      "description": "End date of dispense period, which is determined by the external system. Greater or equal to dispense_valid_from. Format DATE '2017-10-07'"
    },
    "medication_id": {
      "$ref": "#/definitions/uuid",
      "description": "Medication identified"
    },
    "medication_qty": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true,
      "description": "Medication quantity isuued by the doctor"
    },
    "medical_program_id": {
      "$ref": "#/definitions/uuid",
      "description": "Medical program identifier"
    }
  },
  "required": [
    "person_id",
    "employee_id",
    "division_id",
    "created_at",
    "started_at",
    "ended_at",
    "dispense_valid_from",
    "dispense_valid_to",
    "medication_id",
    "medication_qty",
    "medical_program_id"
  ],
  "additionalProperties": false
}

=== lionsoft/ehealth.api/apps/ehealth/test/data/medication_request_request/medication_request_request.json
{
    "person_id": "585044f5-1272-4bca-8d41-8440eefe7d26",
    "employee_id": "7488a646-e31f-11e4-aace-600308960662",
    "division_id": "b075f148-7f93-4fc2-b2ec-2d81b19a9b7b",
    "created_at": "2020-09-22",
    "started_at": "2020-09-22",
    "ended_at": "2020-10-22",
    "dispense_valid_from": "2020-09-25",
    "dispense_valid_to": "2020-10-25",
    "medication_id": "1349a693-4db1-4a3f-9ac6-8c2f9e541982",
    "medication_qty": 10,
    "medical_program_id": "1349a693-4db1-4a3f-9ac6-8c2f9e541981"
}
